name: covid19
# conda env create -f environment.yml
# to remove, simply do conda env remove -n mlpipeline
channels:
    - conda-forge
    - defaults
    - anaconda
dependencies:
    - python=3.7
    - pip
    - numpy
    - pandas
    - matplotlib
    - seaborn
    - statsmodels
    - lmfit
    - xgboost
    - scikit-learn
    - jupyter
    - jupyter_contrib_nbextensions
    - autopep8
    - pandas-profiling
    - imagehash
    - tpot
    - lxml
    - pip:
      - auto-sklearn
      - lightgbm
